# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorldCup2026CliDashboard < Formula
  desc "Watch live World Cup 2026 matches in your terminal"
  homepage "https://github.com/mansueli/world-cup-2026-cli-dashboard"
  version "0.3.6"
  license "MIT"

  on_macos do
    url "https://github.com/mansueli/world-cup-2026-cli-dashboard/releases/download/v0.3.6/world-cup-2026-cli-dashboard_0.3.6_darwin_all.tar.gz"
    sha256 "00223950a453a1ed2a2a4a6ad1b729307a12b9fce5f983971c7c2ba364707377"

    define_method(:install) do
      bin.install "world-cup-2026-cli-dashboard"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mansueli/world-cup-2026-cli-dashboard/releases/download/v0.3.6/world-cup-2026-cli-dashboard_0.3.6_linux_amd64.tar.gz"
      sha256 "e3549cf7bfb60d4380379f12a3a3d38d4d7052a3e99baf288ac3561d1df2b507"
      define_method(:install) do
        bin.install "world-cup-2026-cli-dashboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mansueli/world-cup-2026-cli-dashboard/releases/download/v0.3.6/world-cup-2026-cli-dashboard_0.3.6_linux_arm64.tar.gz"
      sha256 "fcfc679b3e8a405433f2e67949ec4057ebc287df7f67799bc4ad3132ea1d783b"
      define_method(:install) do
        bin.install "world-cup-2026-cli-dashboard"
      end
    end
  end
end
