# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorldCup2026CliDashboard < Formula
  desc "Watch live World Cup 2026 matches in your terminal"
  homepage "https://github.com/mansueli/world-cup-2026-cli-dashboard"
  version "0.4.2"
  license "MIT"

  on_macos do
    url "https://github.com/mansueli/world-cup-2026-cli-dashboard/releases/download/v0.4.2/world-cup-2026-cli-dashboard_0.4.2_darwin_all.tar.gz"
    sha256 "edb83ededdb2b901a217be7ebb9b2563eb135298f53b5b028250b8f31e4d04bf"

    define_method(:install) do
      bin.install "world-cup-2026-cli-dashboard"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mansueli/world-cup-2026-cli-dashboard/releases/download/v0.4.2/world-cup-2026-cli-dashboard_0.4.2_linux_amd64.tar.gz"
      sha256 "6fbccb9362a4e5e362fe956c0387c9837d91805add69a858ac0e1fe732c7a5fc"
      define_method(:install) do
        bin.install "world-cup-2026-cli-dashboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mansueli/world-cup-2026-cli-dashboard/releases/download/v0.4.2/world-cup-2026-cli-dashboard_0.4.2_linux_arm64.tar.gz"
      sha256 "2c879a3cac82409c151753c6f73775f7be53b30c7bbaf6c7d4fec7ab9e4b2698"
      define_method(:install) do
        bin.install "world-cup-2026-cli-dashboard"
      end
    end
  end
end
